#!/usr/bin/env python3
"""Snapshot framework and non-video production files into an independent Git repo."""

import argparse
from collections import Counter
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys

VIDEO = {'.mp4', '.webm', '.mov', '.mkv', '.avi', '.m4v', '.mpg', '.mpeg',
         '.wmv', '.flv', '.ogv', '.mts', '.m2ts', '.3gp', '.mxf'}
DATA = {'.md', '.txt', '.rst', '.json', '.yaml', '.yml', '.toml', '.csv', '.tsv',
        '.html', '.css', '.js', '.jsx', '.ts', '.tsx', '.py', '.sh', '.srt', '.vtt',
        '.png', '.jpg', '.jpeg', '.webp', '.svg', '.gif', '.bmp', '.avif', '.heic',
        '.psd', '.ai', '.pdf', '.wav', '.aiff', '.aif', '.mp3', '.m4a', '.aac',
        '.ogg', '.flac', '.opus'}
SKIP_DIRS = {'.git', 'node_modules', '__pycache__', '.venv', 'venv', '.cache',
             '.pytest_cache', '.ssh', '.aws'}
DATA_ROOTS = ('projects', 'assets', 'pelsona')
LIMIT = 100 * 1024 * 1024
META = '.private-sync/manifest.json'
PUBLIC_IGNORE = '.private-sync/public.gitignore'
NOTICE = 'PRIVATE_COPY.md'
GENERATED = {META, PUBLIC_IGNORE, NOTICE, '.gitignore'}
PRIVATE_IGNORE = '\n'.join([
    '# Generated by scripts/sync-private.py; public rules are in .private-sync/',
    '.git/', 'node_modules/', '__pycache__/', '.venv/', 'venv/', '.cache/',
    '.pytest_cache/', '*.py[cod]', '.DS_Store', '*.log', '.env', '.env.*',
    '*.pem', '*.key', '.npmrc', '.netrc', '.pypirc', 'remotion/out/',
    'remotion/public/', *('*' + suffix for suffix in sorted(VIDEO)), ''])
HOOK = '''#!/bin/sh
# Installed by narrated-video-kit private sync.
exec python3 "$(git rev-parse --show-toplevel)/scripts/sync-private.py" --check-push "$1" "$2"
'''


def run(args, cwd=None, ok=(0,)):
    result = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    if result.returncode not in ok:
        raise ValueError(result.stderr.strip() or result.stdout.strip() or f'Failed: {args[0]}')
    return result.stdout.strip()


def git(root, *args, ok=(0,)):
    return run(['git', '-C', str(root), *args], ok=ok)


def config(root, key):
    return git(root, 'config', '--local', '--get', key, ok=(0, 1))


def safe_path(root, relative):
    rel = Path(relative)
    if rel.is_absolute() or '..' in rel.parts or '.git' in rel.parts:
        raise ValueError(f'Unsafe managed path: {relative}')
    path = root / rel
    for part in (path, *path.parents):
        if part == root:
            break
        if part.is_symlink():
            raise ValueError(f'Symlink is not supported: {part}')
    return path


def digest(path):
    value = hashlib.sha256()
    with path.open('rb') as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b''):
            value.update(chunk)
    return value.hexdigest()


def excluded(relative):
    path = Path(relative)
    if any(part in SKIP_DIRS or part.endswith('.egg-info') for part in path.parts):
        return 'cache/runtime'
    if path.name.startswith('.env') or path.name in {'.npmrc', '.netrc', '.pypirc'} or path.suffix.lower() in {'.pem', '.key'}:
        return 'credentials/config'
    if path.name == '.DS_Store' or path.suffix.lower() in {'.pyc', '.pyo', '.log'}:
        return 'cache/runtime'
    if path.suffix.lower() in VIDEO:
        return 'video'
    if relative.startswith(('remotion/out/', 'remotion/public/')):
        return 'render copies'
    return None


def collect(source):
    candidates = set(filter(None, git(source, 'ls-files', '-z').split('\0')))
    declared_video = set()
    for name in DATA_ROOTS:
        directory = source / name
        if not directory.is_dir() or directory.is_symlink():
            raise ValueError(f'Missing or symlinked data root: {directory}')
        def fail_walk(error):
            raise error

        for current, dirs, files in os.walk(directory, followlinks=False, onerror=fail_walk):
            for child in list(dirs):
                path = Path(current) / child
                if child in SKIP_DIRS:
                    dirs.remove(child)
                elif path.is_symlink():
                    raise ValueError(f'Symlink is not supported: {path}')
            for filename in files:
                candidates.add(str((Path(current) / filename).relative_to(source)))
    for manifest in (source / 'projects').glob('*/project.json'):
        manifest = safe_path(source, str(manifest.relative_to(source)))
        for asset in json.loads(manifest.read_text()).get('assets', {}).values():
            if asset.get('kind') == 'video':
                src = asset.get('src', '')
                safe_path(source, src)
                declared_video.add(src)
    files, skipped = {}, Counter()
    for relative in sorted(candidates):
        reason = excluded(relative)
        if reason or relative in declared_video:
            skipped[reason or 'declared video'] += 1
            continue
        if relative in GENERATED or relative.startswith('.private-sync/'):
            if relative != '.gitignore':
                raise ValueError(f'Reserved snapshot path: {relative}')
            continue
        path = safe_path(source, relative)
        if not path.exists():  # Reflect tracked deletions, without changing source Git.
            continue
        if not path.is_file():
            raise ValueError(f'Not a regular file: {path}')
        if Path(relative).parts[0] in DATA_ROOTS and path.suffix.lower() not in DATA and path.name != '.gitkeep':
            skipped['unsupported data format'] += 1
            continue
        size = path.stat().st_size
        if size > LIMIT:
            raise ValueError(f'File exceeds GitHub 100 MiB limit: {relative}')
        files[relative] = {'bytes': size, 'sha256': digest(path),
                           'executable': bool(path.stat().st_mode & 0o111)}
    return files, skipped


def expected_url(repository):
    if not re.fullmatch(r'[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+', repository):
        raise ValueError('Set privateSync.repository to GitHub OWNER/REPO')
    return f'https://github.com/{repository}.git'


def verify_private(repository):
    expected_url(repository)
    data = json.loads(run(['gh', 'repo', 'view', repository, '--json', 'nameWithOwner,isPrivate']))
    if data.get('isPrivate') is not True or data.get('nameWithOwner', '').lower() != repository.lower():
        raise ValueError('Destination must be the configured PRIVATE GitHub repository')


def validate_destination(source, destination, repository):
    if destination == source or destination.is_relative_to(source) or source.is_relative_to(destination):
        raise ValueError('Private checkout must be separate from the public checkout')
    if not (destination / '.git').is_dir() or (destination / '.git').is_symlink():
        raise ValueError('Private checkout must have its own .git directory (not a worktree)')
    if config(destination, 'privateSync.role') != 'mirror' or config(destination, 'privateSync.repository') != repository:
        raise ValueError('Destination is not the configured private mirror')
    if git(destination, 'branch', '--show-current') != 'main':
        raise ValueError('Private checkout must be on main')
    if git(destination, 'remote').splitlines() != ['private']:
        raise ValueError('Private checkout must have only the private remote')
    url = expected_url(repository)
    if git(destination, 'remote', 'get-url', 'private') != url or git(destination, 'remote', 'get-url', '--push', 'private') != url:
        raise ValueError('Private remote URL does not match configured repository')
    if git(destination, 'status', '--porcelain', '--untracked-files=all'):
        raise ValueError('Private checkout has local changes; inspect them before syncing')
    hooks_path = git(destination, 'config', '--get', 'core.hooksPath', ok=(0, 1))
    if hooks_path:
        raise ValueError('Private checkout has a custom hooksPath; do not bypass its hooks')
    hook = destination / '.git/hooks/pre-push'
    if hook.parent.is_symlink() or hook.is_symlink() or (hook.exists() and hook.read_text() != HOOK):
        raise ValueError('Private checkout already has a different pre-push hook')
    manifest_path = safe_path(destination, META)
    previous = json.loads(manifest_path.read_text())['files'] if manifest_path.exists() else {}
    for relative in previous:
        if relative in GENERATED:
            raise ValueError(f'Reserved path in managed files: {relative}')
        safe_path(destination, relative)
    tracked = set(filter(None, git(destination, 'ls-files', '-z').split('\0')))
    if tracked - set(previous) - GENERATED:
        raise ValueError('Private checkout contains files not managed by this sync')
    return previous


def apply_snapshot(source, destination, repository, files, previous, message):
    # Resolve every destination before any write or removal, including ignored paths.
    for relative in set(files) | set(previous) | GENERATED:
        path = safe_path(destination, relative)
        if path.exists() and not path.is_file():
            raise ValueError(f'File/directory conflict: {path}')
    for relative, info in files.items():
        target = safe_path(destination, relative)
        if previous.get(relative) != info or not target.exists() or digest(target) != info['sha256']:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(safe_path(source, relative), target)
            if digest(target) != info['sha256']:
                raise ValueError(f'Source changed while copying: {relative}')
        target.chmod(0o755 if info['executable'] else 0o644)
    for relative in set(previous) - set(files):
        safe_path(destination, relative).unlink()
    (destination / '.private-sync').mkdir(exist_ok=True)
    (destination / '.gitignore').write_text(PRIVATE_IGNORE)
    (destination / PUBLIC_IGNORE).write_bytes(safe_path(source, '.gitignore').read_bytes())
    (destination / NOTICE).write_text(
        '# Private production snapshot\n\n'
        'This checkout is managed by `scripts/sync-private.py` in the public working repository.\n'
        'It has independent Git history. Do not add a public remote or edit this copy directly.\n'
        'Video files (including demo videos), dependencies and render copies are excluded.\n'
        'Project documents, images, audio, subtitles and source records are preserved.\n'
        'See `docs/private-sync.md` for syncing and restoring into the public working checkout.\n')
    manifest = {'version': 1, 'source_commit': git(source, 'rev-parse', 'HEAD'), 'files': files}
    (destination / META).write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n')
    hook = destination / '.git/hooks/pre-push'
    hook.write_text(HOOK)
    hook.chmod(0o755)
    # Stage only selected paths, never `git add .` or ignored local extras.
    paths = sorted(set(files) | set(previous) | GENERATED)
    staged = subprocess.run(['git', '-C', str(destination), '--literal-pathspecs', 'add', '-f',
                             '--pathspec-from-file=-', '--pathspec-file-nul'],
                            input='\0'.join(paths) + '\0', text=True, capture_output=True)
    if staged.returncode:
        raise ValueError(staged.stderr)
    if git(destination, 'diff', '--cached', '--name-only'):
        git(destination, 'commit', '--quiet', '-m', message)
        print('Private commit: ' + git(destination, 'rev-parse', '--short', 'HEAD'))
    else:
        print('Private snapshot already up to date.')


def push_guard(root, remote, url):
    repository = config(root, 'privateSync.repository')
    if config(root, 'privateSync.role') != 'mirror' or remote != 'private' or url != expected_url(repository):
        raise ValueError('Private snapshots may only be pushed to their configured private remote')
    verify_private(repository)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--apply', action='store_true', help='Copy and commit; default is read-only planning')
    parser.add_argument('--push', action='store_true', help='Copy, commit and push to private/main')
    parser.add_argument('--list', action='store_true', help='Include all selected paths in the plan')
    parser.add_argument('--message', default='Sync framework and non-video production records')
    parser.add_argument('--check-push', nargs=2, metavar=('REMOTE', 'URL'), help=argparse.SUPPRESS)
    args = parser.parse_args()
    source = Path(__file__).resolve().parents[1]
    if args.check_push:
        push_guard(source, *args.check_push)
        return
    if config(source, 'privateSync.role') == 'mirror':
        raise ValueError('Run the sync from your public working checkout, not the private snapshot')
    directory = config(source, 'privateSync.directory')
    repository = config(source, 'privateSync.repository')
    if not directory or not repository:
        raise ValueError('Configure privateSync.directory and privateSync.repository; see docs/private-sync.md')
    destination = Path(directory).expanduser().resolve()
    previous = validate_destination(source, destination, repository)
    files, skipped = collect(source)
    summary = {'repository': repository, 'files': len(files),
               'bytes': sum(item['bytes'] for item in files.values()),
               'added': len(set(files) - set(previous)),
               'changed': sum(previous[p] != files[p] for p in files.keys() & previous.keys()),
               'removed': len(set(previous) - set(files)), 'excluded': dict(skipped)}
    if args.list:
        summary['paths'] = list(files)
    print(json.dumps(summary, ensure_ascii=False, indent=2), flush=True)
    if not (args.apply or args.push):
        return
    verify_private(repository)
    if args.push:
        git(destination, 'fetch', 'private')
        remote_head = git(destination, 'rev-parse', '--verify', '--quiet', 'refs/remotes/private/main', ok=(0, 1))
        if remote_head:
            git(destination, 'merge-base', '--is-ancestor', remote_head, 'HEAD')
    apply_snapshot(source, destination, repository, files, previous, args.message)
    if args.push:
        print(git(destination, 'push', '--set-upstream', 'private', 'main:main'))
        print('Pushed to ' + expected_url(repository))


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError, KeyError, TypeError, json.JSONDecodeError) as error:
        print(f'Error: {error}', file=sys.stderr)
        sys.exit(1)
